/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'abghode' at '8/19/17 8:02 PM' with Gradle 2.13
 *
 * @author abghode, @date 8/19/17 8:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
