/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'abghode' at '5/27/16 6:05 PM' with Gradle 2.13
 *
 * @author abghode, @date 5/27/16 6:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
